name: planning_system
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  dartz: ^0.10.1
  dotenv: ^4.2.0
  flutter_dotenv: ^5.1.0
  drift: ^2.28.2
  drift_flutter: ^0.2.7
  excel: ^4.0.6
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.1
  get: ^4.7.2
  open_file: ^3.5.10
  path: ^1.9.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  window_manager: ^0.5.1

dev_dependencies:
  build_runner: ^2.7.1
  drift_dev: ^2.28.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/json/
    - .env
  fonts:
    - family: Arimo
      fonts:
        - asset: assets/fonts/Arimo-VariableFont_wght.ttf

flutter_assets:
  assets_path:
    - assets/images/
    - assets/icons/
  output_path: lib/core/utils/
  filename: assets.dart
  field_prefix: null
