name: planning_system
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.1
  get: ^4.7.2
  excel: ^4.0.6
  file_picker: ^10.3.3
  dartz: ^0.10.1
  window_manager: ^0.5.1
  drift: ^2.28.2
  drift_flutter: ^0.2.7
  path_provider: ^2.1.5

dev_dependencies:
  drift_dev: ^2.28.3
  build_runner: ^2.7.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: Arimo
      fonts:
        - asset: assets/fonts/Arimo-VariableFont_wght.ttf

flutter_assets:
  assets_path: assets/icons/
  output_path: lib/core/utils/
  filename: assets.dart
  field_prefix: null
