import 'dart:ui';

import 'package:planning_system/core/database/db.dart';
import 'package:planning_system/core/enums/grade.dart';

const kWindowSize = Size(1100, 700);

const kCellPadding = 8.0;

typedef ColorPair = ({Color dark, Color light});

const kgradesData = <Grade>[
  Grade(codeGrade: GradeEnum.pr, label: 'Professeur', nbOfSeance: 4),
  Grade(codeGrade: GradeEnum.mc, label: 'Maitre de Conférences', nbOfSeance: 4),
  Grade(codeGrade: GradeEnum.ma, label: 'Maitre Assistant', nbOfSeance: 7),
  Grade(codeGrade: GradeEnum.as, label: 'Assistant', nbOfSeance: 8),
  Grade(codeGrade: GradeEnum.ac, label: 'Assistant Contractuel', nbOfSeance: 9),

  Grade(
    codeGrade: GradeEnum.ptc,
    label: 'Professeur Tronc Commun',
    nbOfSeance: 9,
  ),
  Grade(
    codeGrade: GradeEnum.pes,
    label: 'Professeur d’enseignement secondaire',
    nbOfSeance: 9,
  ),

  Grade(codeGrade: GradeEnum.ex, label: 'Expert', nbOfSeance: 3),
  Grade(codeGrade: GradeEnum.v, label: 'Vacataire', nbOfSeance: 4),
];

const kgradesDataV2 = <GradeEnum, Grade>{
  GradeEnum.pr: Grade(
    codeGrade: GradeEnum.pr,
    label: 'Professeur',
    nbOfSeance: 4,
  ),
  GradeEnum.mc: Grade(
    codeGrade: GradeEnum.mc,
    label: 'Maitre de Conférences',
    nbOfSeance: 4,
  ),
  GradeEnum.ma: Grade(
    codeGrade: GradeEnum.ma,
    label: 'Maitre Assistant',
    nbOfSeance: 7,
  ),
  GradeEnum.as: Grade(
    codeGrade: GradeEnum.as,
    label: 'Assistant',
    nbOfSeance: 8,
  ),
  GradeEnum.ac: Grade(
    codeGrade: GradeEnum.ac,
    label: 'Assistant Contractuel',
    nbOfSeance: 9,
  ),
  GradeEnum.ptc: Grade(
    codeGrade: GradeEnum.ptc,
    label: 'Professeur Tronc Commun',
    nbOfSeance: 9,
  ),
  GradeEnum.pes: Grade(
    codeGrade: GradeEnum.pes,
    label: 'Professeur d\'enseignement secondaire',
    nbOfSeance: 9,
  ),
  GradeEnum.ex: Grade(codeGrade: GradeEnum.ex, label: 'Expert', nbOfSeance: 3),
  GradeEnum.v: Grade(codeGrade: GradeEnum.v, label: 'Vacataire', nbOfSeance: 4),
};

const Map<String, String> kEnseignantMap = {
  "R.MZID": "75",
  "S.MHENI": "48",
  "N.BEN YOUSSEF": "65",
  "W.MILADI": "15",
  "A.KROUMI": "375",
  "M.FRIKHA": "219",
  "H.AISSA": "13",
  "Y.MANAI": "38",
  "Y.BANNOUR": "115",
  "F.DKHIL": "5",
  "M.BOUBAKRI": "401",
  "N.BRIDAA": "118",
  "I.DALDOUL": "157",
  "A.KHALFALLAH": "55",
  "H.BEN FRADJ": "25",
  "A.BIDANI": "232",
  "T.KHEMIRI": "117",
  "B.ZINA": "159",
  "I.BOUSAOUDIA": "108",
  "A.MARZOUKI": "130",
  "W.YOUSSEF": "60",
  "R.ABED": "135",
  "R.ZAAFRANI": "62",
  "S.REJICHI": "51",
  "M.BEN REGAIA": "116",
  "M.GOUYAEIB": "206",
  "S.TOUJ": "23",
  "I.LASSOUED": "76",
  "W.KAROUI": "57",
  "N.AROUS": "3",
  "S.RAJIA": "80",
  "A.KHIMIRI": "91",
  "H.BEN ISHAK": "127",
  "Z.BEN AZZOUZ": "29",
  "R.BEN ELAKHAL": "110",
  "Z.ZOUAIGHIA": "207",
  "S.ELAOUD": "18",
  "H.METOUI": "19",
  "M.FEKI": "35",
  "A.CHETOUANE": "320",
  "K.MARZOUKI": "72",
  "H.AYOUB": "371",
  "S.TLILI": "225",
  "F.YAHYA": "128",
  "F.OUESLATI": "112",
  "I.HAMMI": "99",
  "I.BELHOUENE": "100",
  "H.MOGAADI": "96",
  "G.BESBES": "77",
  "G.ESSAIED": "166",
  "S.BAHROUN": "66",
  "M.NENNI": "238",
  "L.DERBAL": "17",
  "K.BANENE": "188",
  "S.SALHI": "187",
  "Z.CHANNOUF": "113",
  "A.OULED ZAIED": "8",
  "M.OUERTANI": "45",
  "K.BOURIEL": "119",
  "A.TLILI": "11",
  "K.SAMMOUD": "56",
  "S.ZAHAF": "84",
  "Y.BEN SOULA": "227",
  "N.BELLAAJ MRABET": "6",
  "M.AJABI": "39",
  "M.KALLEL": "50",
  "C.BACCAR": "12",
  "H.BEN KRID": "240",
  "H.OUERGHI": "223",
  "S.BEN REJEB": "44",
  "S.ZAOULI": "102",
  "A.YOUNES": "216",
  "I.REKIK": "20",
  "H.CHAABOUNI": "34",
  "R.BEN HENDA": "104",
  "O.LIMAM": "87",
  "I.SANSA": "197",
  "D.BEN AYED": "22",
  "A.BEL HADJ ALI": "98",
  "N.ANNABI": "78",
  "E.ZAGHROUBA": "1",
  "I.AYACHI": "37",
  "I.BEN HFAIEDH": "63",
  "R.KAMMARTI": "27",
  "O.BEN SASSI": "40",
  "M.LOGHMARI": "43",
  "A.NAFTI": "120",
  "H.BEN ABDALLAH": "88",
  "O.MOURALI": "82",
  "R.GADDOUR": "380",
  "G.ZHIOUA": "71",
  "S.BOUAJINA": "46",
  "W.ARFA": "311",
  "H.MIBAR": "32",
  "A.TOUIHRI": "125",
  "Y.NAJAR": "92",
  "F.CHOURA": "90",
  "O.KHOUJA": "300",
  "H.LIMAM": "86",
  "M.GUESMI": "450",
  "M.HELAOUI": "143",
  "I.HMOUDA": "33",
  "W.MRABET": "74",
  "M.FERCHICHI": "53",
  "A.BEN MILED": "315",
  "L.SAMIR": "109",
  "M.NAJJAR": "9",
  "C.SEDDIK": "26",
  "A.BORGI": "4",
  "R.ZAGROUBA": "67",
  "N.BOULIFA": "111",
  "R.KAABI": "58",
  "F.BEN AICHA": "36",
  "N.BEN HARIZ": "97",
  "B.HAOUARI": "101",
  "M.GLAOUI": "350",
  "M.HACHANI": "52",
  "A.AYARI": "236",
  "S.MASMOUDI TOUJ": "24",
  "S.OUALI": "777",
  "L.LANDOLSI": "107",
  "F.KATLANE KATEB": "89",
  "S.MZOUGHI": "106",
};
